### ISSUE TITLE
License Question - GPLv3 Intentional?

### ISSUE THREAD

**Issue by KuriousKoder** [sentry07/netlinx-libJSON#2]
I'm not 100% certain this is the best way to as I'm new to this...  but I was looking at your library to use for an internship project; however, in compsci, I remembering them saying that the GPL-3.0 License you've selected is CopyLeft...  here's some info:

If I'm using a GPL 3 library in my project, can I license my project under MIT license?
○ https://opensource.stackexchange.com/a/1641/20633
(... _though not the license we're using, it explains the effects of CopyLeft_.)

Also, from a business perspective, our professor had us review this article:
○ https://www.synopsys.com/blogs/software-security/top-open-source-licenses/

I don't think GPLv3 will work for our project (_or probably any non-hobby AMX project, as it's a pretty business'ey proprietary lang_), because the overall project code belongs to the company/clients...  and with CopyLeft, that's not possible.  Also, perhaps that's why your library isn't getting more stars, as businesses can't use it.  That being said, I don't think there'd be any problems with attribution and/or committing any modifications into the public that are library specific, as I've already done that for an open source MIT library.  Is there any chance that you'd consider a more permissive MIT or Apache v2 License?

Thanks, happy new year & stay safe...

**Comment by sentry07** [comment]
I thought GPL 3 was non restrictive. Guess I misunderstood it. I changed it to Apache 2.0.
